import { createElement } from '@lwc/engine-dom';
import LwcBasicCaseStudy7 from 'c/lwcBasicCaseStudy7';

describe('c-lwc-basic-case-study7', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-basic-case-study7', {
            is: LwcBasicCaseStudy7
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});